import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "MyDO - 404",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <h1>ERRO 404</h1>
    );
}